#!/bin/bash
while :
do
        if [ -f "/var/tmp/.../tom/result.txt" ];then
                ip=$(curl ifconfig.me)
                d=$(date)
                sleep 5s
                echo $ip $d | mail -s "tom" salahei006@proton.me
        fi
        sleep 24h
done
